// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5V0uQ541GBzPmLM1klqTXevPScmzJ5FE',
    appId: '1:704785699055:web:f3eae1af7827ce365bcb1a',
    messagingSenderId: '704785699055',
    projectId: 'hrproject-ee215',
    authDomain: 'hrproject-ee215.firebaseapp.com',
    storageBucket: 'hrproject-ee215.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDytKs20fIdY3GXnfkK74F9Ifs1eCPXx4k',
    appId: '1:704785699055:android:9f01884f742b386f5bcb1a',
    messagingSenderId: '704785699055',
    projectId: 'hrproject-ee215',
    storageBucket: 'hrproject-ee215.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuNkmvSkL9-ISf-4aoTXMBg4hE2jO5dSM',
    appId: '1:704785699055:ios:97669ded2aef8bc85bcb1a',
    messagingSenderId: '704785699055',
    projectId: 'hrproject-ee215',
    storageBucket: 'hrproject-ee215.appspot.com',
    iosClientId: '704785699055-1d5vrq63l1dg41sjlfd8bv4qease4pub.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
